### ISSUE TITLE
brainstorm statistics and metrics for the dashboard

### ISSUE THREAD

**Issue by fogx** [jina-ai/docsQA-ui#91]
Current issues / open questions regarding statistics

- questionType is not always set - is this a bug or a feature?
- the rating (thumbs) are VERY hard to see/ find.
- thumbs down should not be the default -> it should be a specific event (three categories)
- how persistent is the user_id? -> is it only one session?

**Comment by azayz** [comment]
## Build a question/answer aggregation tool to be able to select what we want
1. Add source URL
2. Use general telemetry (like location, device, language)
3. Count of thumbs up / total requests , Count of thumbs down / total requests, Count of not using thumbs at all / total requests
4. Number of bot usage compared to visits (check with Yanlong) (if too low maybe add annoying thing that says talk to me)
5. Number of requests per day per week per month, what time of day
6. Percentage of typed vs suggested questions compares to the total number of questions (after we fix the issue of missing type for some requests)
7. how many times the bot is not confident
8. show qa and add filter options
9. average questions per client_id (for a client how many questions are asked)

**Comment by nan-wang** [comment]
clarify the meaning of `thumb_up` field. @Hippopotamus0308

**Comment by nan-wang** [comment]
verify that all the collected data have `questionType` @Hippopotamus0308

**Comment by Hippopotamus0308** [comment]
towards `thumbup`, I will judge the value in the script, if there is no `thumbup`, this value will be set as `undefined`, but towards `questionType` value, currently I haven't figured out a good way to solve it. Shall I also set it as `undefined`?

**Comment by fogx** [comment]
why is questionType not kept when feedback is given? Best way to solve it is to just always keep it?

**Comment by fogx** [comment]
[current design document for the dashboard](https://www.notion.so/Dashboard-Design-Document-d54b19d2dc2d49e5993292a3aa278b3e)
next step: meet with kelly to plan design

**Comment by fogx** [comment]
@nan-wang please review the design document for the dashboard
